"""empty message

Revision ID: 4623373ae84e
Revises: 5179f034a4b5
Create Date: 2015-12-09 17:09:34.611716

"""

# revision identifiers, used by Alembic.
revision = '4623373ae84e'
down_revision = '5179f034a4b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'reset_password_token', type_=sa.String(length=150), existing_type=sa.String(length=150), server_default='', nullable=False),
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'reset_password_token', type_=sa.String(length=150), existing_type=sa.String(length=100), server_default='', nullable=False),
    ### end Alembic commands ###
