"""empty message

Revision ID: 5179f034a4b5
Revises: 39769d358276
Create Date: 2015-12-03 17:46:59.153192

"""

# revision identifiers, used by Alembic.
revision = '5179f034a4b5'
down_revision = '39769d358276'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=255), nullable=False))
    ### end Alembic commands ###
